# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3-stretch-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache            
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # See what version is in used
      - run: node -v  && npm -v        
      # run tests!
      - run: npm test

      - store_artifacts:
         path: ~/repo/cypress/screenshots/
